

$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base.mk)


PRODUCT_DEVICE := s3_h560
PRODUCT_NAME := omni_s3_h560
PRODUCT_BRAND := JIAYU
PRODUCT_MODEL := JIAYU S3
PRODUCT_MANUFACTURER := JIAYU 

